### ISSUE TITLE
For Awareness: @sls-next/cdk-construct

### ISSUE THREAD

**Issue by shishkin** [rayova/cdk-serverless-nextjs#66]
Thanks for creating this construct and publishing it on the Construct Hub! 🙏 

I'm sure you might be aware that @sls-next also has an experimental CDK construct: https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/serverless-components/nextjs-cdk-construct. Just wondering if limited OSS efforts could be consolidated for everyone's benefit?

**Comment by misterjoshua** [comment]
Thanks for pointing out this other project. We're open to consolidating efforts where we can, but for now, we require this repository's construct due to our unique requirements. In the meantime, we'll keep an eye on the other project for anything we can contribute.
